version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - airflow_network

  mongo:
    image: mongo:4
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - airflow_network

  webserver:
    image: apache/airflow:2.2.3
    environment:
      LOAD_EX: n
      EXECUTOR: CeleryExecutor
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./operators:/opt/airflow/operators
    command: bash -c "pip install -r /opt/airflow/dags/requirements.txt && airflow db init && airflow db migrate && airflow db upgrade && airflow webserver"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - mongo
    env_file:
      - .env
    networks:
      - airflow_network

  worker:
    image: apache/airflow:2.2.3
    command: celery worker
    environment:
      LOAD_EX: n
      EXECUTOR: CeleryExecutor
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./operators:/opt/airflow/operators
    command: bash -c "pip install -r /opt/airflow/dags/requirements.txt && airflow worker"
    depends_on:
      - postgres
      - mongo
    env_file:
      - .env
    networks:
      - airflow_network

networks:
  airflow_network:

volumes:
  postgres_data:
  mongo_data:
