version: '3'

services:
  minio1:
    image: minio/minio
    container_name: minio1
    env_file:
      - ./.env
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    volumes:
      - minio-data-1:/data
    command: server http://minio{1...2}/data
    networks:
      - minio-network

  minio2:
    image: minio/minio
    container_name: minio2
    env_file:
      - ./.env
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    volumes:
      - minio-data-2:/data
    command: server http://minio{1...2}/data
    networks:
      - minio-network

  # Simple UI for MinIO Object Storage
  minio-console:
    image: minio/console
    container_name: minio-console
    env_file:
      - ./.env
    environment:
      MINIO_BROWSER_DEFAULT_ROOT: minio1
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    ports:
      - "9001:9001"
      - "9090:9090"
    depends_on:
      - minio1
    networks:
      - minio-network
    command: server /data

  haproxy:
    image: haproxytech/haproxy-alpine:2.7
    container_name: minio_haproxy
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - '9000:9000'
      - '1936:1936'
    networks:
      - minio-network

volumes:
  minio-data-1:
  minio-data-2:

networks:
  minio-network:
    driver: bridge